#import "GeneratedPluginRegistrant.h"

// Generated by media_kit_video's podspec, and only while media_kit_libs_ios_video
// is in the graph. PiPController reads the mpv render context through these to
// share frames with the AVSampleBufferDisplayLayer.
#include "../.symlinks/plugins/media_kit_video/ios/Headers/mpv/client.h"
#include "../.symlinks/plugins/media_kit_video/ios/Headers/mpv/render.h"
